### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by YuraLi88** [seermer/EfficientNetV2_TensorFlow2#1]
Thank you for the clean and simple implementation of EffNetV2!
Are you planning to sync your implementation with the official repository (https://github.com/google/automl/tree/master/efficientnetv2)?

**Comment by seermer** [comment]
Hi, glad if this helps.

However, sorry, I think I will not be able to sync recently.
Although I have started looking into official codes, I noticed that their code seems to be different from what is claimed in the paper, see below, so I am very confused about it.
Since my primary goal of this repo was to practice while reading the paper, I don't want to change it blindly to follow the official code, I will investigate and study further before making any change.

**considering such differences, I would suggest you directly use the code from the official repo instead if you need it. Because most unofficial codes like mine followed the config in the paper (I read several other open-source unofficial codes, and their # of param matches mine, differs from official codes), which results in different architecture and # params.**
______________________________

from the original paper:
![image](https://user-images.githubusercontent.com/49250812/118385980-5c73f000-b646-11eb-8b5f-d0095438bd61.png)

from official implementation:
![image](https://user-images.githubusercontent.com/49250812/118386080-4e729f00-b647-11eb-9e97-c6cabc06b718.png)

note that in stage 6, the paper uses 272 channels(filters), but the official configuration uses 256 channels(filters)

_____________________________

besides this significant difference, there are also minor differences like no drop connect in paper vs drop connect in code etc. And these differences cause about 3M param difference, which is quite a lot, I may need to wait and see why.

**Comment by seermer** [comment]
Hi, just an update, I asked in their official repo, it seems like they changed their minds after submitting the paper because they believe the new architecture in code is more hardware friendly. They will also update the paper soon. According to their member:

> please use the code as the source of truth

I managed to modify my repo today, and now EfficientNetV2-s, m, l, xl all have the same parameter as the original repo.\
And ghost efficientnet is also using the new architecture as official repo with Ghost module instead of normal conv.\
~~Before then, I will try to sync with their code, but since it no longer matches exactly with paper, it will be relatively difficult for me. I would still suggest you using the official code since it also uses TF2, sorry for the inconvenience~~

**Comment by seermer** [comment]
Hi, just an update, I asked in their official repo, it seems like they changed their minds after submitting the paper because they believe the new architecture in code is more hardware friendly. They will also update the paper soon. According to their member:

> please use the code as the source of truth

Before then, I will try to sync with their code, but since it no longer matches exactly with paper, it will be relatively difficult for me. I would still suggest you using the official code since it also uses TF2, sorry for inconvinience
