### ISSUE TITLE
train custom object detection model using efficiennetv2

### ISSUE THREAD

**Issue by akashAD98** [seermer/EfficientNetV2_TensorFlow2#2]
thanks for your TensorFlow implementation, can you please make detailed steps about how can we train our own OD model using this efficientNetv2? it wold be great help

**Comment by seermer** [comment]
Sorry for the very late response, I was previously busy with something else.

I don't think you can use this model directly for OD, as this model is implemented as a classifier just like the official repo.
However, you may customize based on the blocks and models I implemented. Since I built the model with blocks implemented as functions, you can insert branches to OD heads after the blocks of your choice.

**Comment by seermer** [comment]
I am closing this issue, if you have any other questions, feel free to reopen
