### ISSUE TITLE
Using official weights

### ISSUE THREAD

**Issue by Jogima-cyber** [seermer/EfficientNetV2_TensorFlow2#3]
Would it be possible to load the official weights into the models of this keras implementation?

**Comment by seermer** [comment]
Sorry, but honestly I don't think so, because I took a completely different way to implement it.

The official repo uses layers.Layer class to implement each block, which means you cannot track any intermediate layers. I implemented each block with functions, which allows tracking intermediate blocks. 
Saved weights are saved according to the model structure, so it is most likely not going to match when you try to load, and I honestly don't know how to convert.

I made this implementation just for easier customization and debugging (in my personal opinion) since you can easily track layers and use this model in personal projects. If you want to use official weights, it is probably best to use the official repo.

**Comment by Jogima-cyber** [comment]
Thank you for your answer.
